# Generated by Django 4.1 on 2022-08-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accrual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrual',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April')], null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April')], null=True),
        ),
    ]
