# Generated by Django 4.1 on 2022-08-31 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accrual', '0003_alter_accrual_month_alter_payment_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='accrual',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accrual.accrual'),
        ),
    ]
